### ISSUE TITLE
`No retryable tickets` error when trying to deposit L2->L3 with USDC

### ISSUE THREAD

**Issue by elclandestin0** [G7DAO/protocol#189] opened 2024-11-20 11:49 UTC
To reproduce:
- Go to [staging](https://build.game7test.io)
- Go to Bridge
- Select Mainnet
- Select Arbitrum One in the From chain
- Try bridging

Expected result: see image
![image](https://github.com/user-attachments/assets/367354d7-d65e-4e88-b1d5-30d5d7d33222)

**Comment by Anton-Mushnin** [comment] 2024-11-22 08:30
Error actually is 'transfer amount exceeds allowance' and caused by the wrong spender logic in the SDK. 
Can't be resolved by now, because the official circle USDC implementation is not configured in the canonical bridge
#199

**Closed by Anton-Mushnin** 2024-11-22 08:30 UTC
